src/osgEarthUtil/EarthManipulator, src/osgEarthUtil/EarthManipulator.cpp
Default value remains at 0.2 seconds, so impact on existing projects is unlikely.
=> EarthManipulator: OPTION_DURATION for Settings::bindScroll()

src/osgEarth/ShaderUtils.cpp, src/osgEarthAnnotation/AnnotationNode.cpp, src/osgEarthFeatures/FeatureModelSource.cpp, src/osgEarthUtil/Sky.cpp
OpenGL ES 2.0 on Windows discussion: http://forum.osgearth.org/OpenGL-ES-2-0-on-Windows-td7587158.html
Some fixes:
* **GL_CLIP_PLANE0** is not available in OpenGL ES 2.0
* **_lightingUniformsHelper** field in **Sky** class is never initialized
* Nodes without Material attribute are shown black because **_frontLightProduct** has zero vectors.
I tested this changes with osgEarth 2.6 version.
=> OpenGL ES 2.0 fixes

src/osgEarth/GeoData.cpp, src/osgEarth/TerrainLayer.cpp, src/osgEarth/TileSource.cpp, src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp
If neither a "warp profile" nor "override profile" are supplied, create a profile from the dataset's own SRS, and return an error if this fails.  Do not fall back to the global geodetic (or global mercator) profile.
Also, add some OE_DEBUG log statements to help users diagnose Profile/SRS issues.
See http://forum.osgearth.org/GDAL-driver-Profile-selection-td7587267.html
=> Improve Profile selection logic in GDAL driver

src/osgEarth/GeoData.cpp, src/osgEarth/VerticalDatum, src/osgEarth/VerticalDatum.cpp, src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp
Comments:
src/osgEarth/GeoData.cpp
_srs has no VerticalDatum
rhs.getSRS() has VerticalDatum
So only horizontal srs should be compared
src/osgEarth/VerticalDatum
virtual methods for more freedom in VerticalDatum subclassing
src/osgEarth/VerticalDatum.cpp
usually we want output units to be meters
src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp
these two deleted lines restrict raw heights and duplicate
if (v < getNoDataMinValue()) return false;
if (v > getNoDataMaxValue()) return false;
=> Fixes to use VerticalDatums with different units

src/osgEarth/Decluttering.cpp, src/osgEarth/PhongLightingEffect.cpp, src/osgEarth/ThreadingUtils.cpp, src/osgEarthDrivers/script_engine_duktape/duktape.h, src/osgEarthUtil/LogarithmicDepthBuffer.cpp
This pull request contains five changes I had to make to get the 2.7rc1 branch to build for Android, but I still have rendering issues to investigate. Two of these changes I am not particularly happy with and probably require some discussion.
Duktape was failing to compile because it couldn't determine `intptr` type (duktape.h, line 1006). I followed the #defines back up to the change and check for `__ANDROID__` in the `DUK_F_X86` conditions. This is fine for us because we are only compiling for 32bit platforms. The Duktape documentation says that on Android it needs to be compiled with `-std=c99`, however adding this to my C_FLAGS didn't solve the problem. I couldn't find way to check for 64bit Android at compile time, perhaps `(defined(__ANDROID__) && !defined(__x86_64__))` would work, …
=> osgearth 2.7rc1 Android build

src/osgEarth/VirtualProgram.cpp
The ARM MALI GLSL compiler chokes on `"` characters:
>  0:20: L0001: Unknown character '"'(34)
These only appear in the `#pragma` lines of the shaders, so drop these lines when parsing shaders for merging.
=> Android build - fix shaders

src/osgEarthDrivers/kml/KML_Feature.cpp, src/osgEarthDrivers/kml/KML_Placemark.cpp, src/osgEarthDrivers/kml/rapidxml_ext.hpp, src/osgEarthUtil/AutoClipPlaneHandler.cpp
Fixed eye computation in AutoClipPlaneHandler to work under RTT camera.
Minor KML fixes: read CDATA node, read extended data.
Added KML annotations to ObjectIndex.
=> KML and AutoClipPlaneHandler fixes

src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp
In case of failures (1) and (2) print warning messages
(1) failure to create copy
(2) failure to invert _geotransform
=> Fix GDAL Warning about unused result

src/osgEarthDrivers/feature_ogr/FeatureCursorOGR.cpp
This fixes a bug where using a csv/vrt file pair with the ogr feature driver would cause a SQL Expression error if the file name contained a hyphen.
=> Quote layer name for VRT files

src/osgEarthAnnotation/GeoPositionNodeAutoScaler, src/osgEarthAnnotation/GeoPositionNodeAutoScaler.cpp, src/osgEarthAnnotation/ModelNode.cpp, src/osgEarthSymbology/ModelSymbol, src/osgEarthSymbology/ModelSymbol.cpp
Usage:
style.getOrCreate<osgEarth::Annotation::ModelSymbol>()->minAutoScale()=3.0;
style.getOrCreate<osgEarth::Annotation::ModelSymbol>()->maxAutoScale()=100.0;
=> Added minimum and maximum scale property for auto-scale model

src/osgEarthDrivers/feature_ogr/FeatureSourceOGR.cpp
This patch avoid the creation of a new PostGIS connection each time a dirty is called on a model source
=> Patch for number of PostGIS connection

src/osgEarth/Decluttering, src/osgEarth/Decluttering.cpp, src/osgEarthAnnotation/LabelNode, src/osgEarthAnnotation/LabelNode.cpp, src/osgEarthAnnotation/PlaceNode, src/osgEarthAnnotation/PlaceNode.cpp, src/osgEarthDrivers/label_annotation/AnnotationLabelSource.cpp, src/osgEarthSymbology/TextSymbol, src/osgEarthSymbology/TextSymbol.cpp, tests/annotation.earth
Two new attributes on TextSymbol:
- text-rotation: absolute on-screen rotation
- text-geographic-course: compute the on-screen rotation for following
a fixed course on ground (use for naming rivers or roads)
Can be tested with annotation.earth (see the tesselated line)
=> Rotation on LabelNode and PlaceNode

src/osgEarthDrivers/feature_ogr/FeatureCursorOGR, src/osgEarthDrivers/feature_ogr/FeatureCursorOGR.cpp
It is similar to the commit f255796eb347687fffe54286a2b0af42eb2bd957 which
seems to having been lost during refactor operations
=> Avoid an infinite loop on Spatialite driver

src/osgEarthAnnotation/AnnotationUtils.cpp, src/osgEarthSymbology/TextSymbol, src/osgEarthSymbology/TextSymbol.cpp
Added access to osgText::Text's backdropType() and backdropImplementation() in TextSymbol.  This allows users of annotation text to change from outline to different backdrop styles.
=> Backdrop type and implementation optionals added to TextSymbol.

src/osgEarth/URI.cpp
@gwaldron added options to most caching functions a month ago, whoever the options did not pass to CacheBin write method.
=> Fix unsetting options of CacheBin write in URI class

src/osgEarthUtil/Controls, src/osgEarthUtil/Controls.cpp
- Add the setVisible method to correctly show/hide the grid and its content.
- Correction of the crash when setVisible(false) is called.
@see:
http://forum.osgearth.org/Problem-with-Utils-Controls-Grid-td7582005.html#a7582220
Many thanks :)
=> Crash on Control::Grid::setVisible

src/osgEarth/ModelLayer, src/osgEarth/ModelLayer.cpp
==16201==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc7003efe0 at pc 0x7f6c52fddcbc bp 0x7ffc7003e4b0 sp 0x7ffc7003e4a0
WRITE of size 8 at 0x7ffc7003efe0 thread T0
#0 0x7f6c52fddcbb in osgEarth::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::optional() /home/agelas/debug/install/include/osgEarth/optional:33
#1 0x7f6c4181ae2d in osgEarth::ModelLayerOptions::ModelLayerOptions(osgEarth::ConfigOptions const&) /home/agelas/source/osgearth/src/osgEarth/ModelLayer.cpp:52
Add copy constructor and assignment operator to avoid implicit convertion
=> Fix bug detected by asan on linux

src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp
Especially when using compressed TIFF heighmaps, the terrain performance suffers a lot from the many 1-pixel RasterIOs performed in `getInterpolatedValue`. This pull-request adds a fast path when using nearest neighbor interpolation, which reads the entire tile in one go via RasterIO. On my machine I easily get a factor 8 speedup with this path using a LZW compressed DTM.
=> Add fast RasterIO sampling path for generating heightfields with nearest neighbor

docs/source/data.rst, docs/source/developer/utilities.rst, docs/source/references/drivers/cache/filesystem.rst, docs/source/references/earthfile.rst, docs/source/references/symbology.rst, docs/source/user/caching.rst
These just caught my eye while I was reading the docs, so I thought I would put them to rest.
=> Fix some really minor typos in docs

src/osgEarthUtil/Controls
Without this, the following type of code will leave strange artifacts:
`Control* menu = createMenu();  // Actually returns a VBox with several labels, grids, etc. under it`
`menu->setVisible(false);`
=> Control setVisible() is now virtual.

src/osgEarthSilverLining/SilverLiningAPIWrapper.cpp
g++ did not like the `<::Namespace` style of `static_cast` and required spaces after the open angle bracket.
=> Fixed Linux g++ compile error.

src/osgEarthSilverLining/SilverLiningContext.cpp
Instead of adding my own ifdef that mirrored SILVERLINING_API's, I just used SILVERLINING_API.  On _WIN32 it's defined as __cdecl; see SilverLining/MemAlloc.h.
=> SL: Win32 build fix; Win32 requires cdecl to properly override.

docs/source/user/tools.rst, src/applications/osgearth_package/osgearth_package.cpp, src/applications/osgearth_seed/osgearth_seed.cpp, src/osgEarth/GPUClamping.vert.lib.glsl, src/osgEarthDrivers/osg/OSGTileSource.cpp, src/osgEarthFeatures/ExtrudeGeometryFilter.cpp
These spelling errors were reported by the lintian QA tool for the Debian package build:
* proceses    -> processes
* Faild       -> Failed
* indiciating -> indicating
=> Fix spelling errors.

src/applications/osgearth_demo/CMakeLists.txt, src/applications/osgearth_package_qt/CMakeLists.txt, src/applications/osgearth_qt_simple/CMakeLists.txt, src/applications/osgearth_qt_windows/CMakeLists.txt
This patch has been included in Debian package for a while, and originates from the Fedora package.
It fixes this build failure:
```
/usr/bin/ld: CMakeFiles/application_osgearth_package_qt.dir/package_qt.cpp.o: undefined reference to symbol 'XInitThreads'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
```
Author: Sandro Mani <manisandro@gmail.com>
Origin: https://kojipkgs.fedoraproject.org//packages/osgearth/2.6/4.fc22/src/osgearth-2.6-4.fc22.src.rpm
=> Link X11 to fix FTBFS.

src/osgEarthUtil/Sky
We have a small null-object implementation of SkyNode in SIMDIS SDK (simUtil::NullSkyModel) that returns NULL on getSunLight().  While we can fix this on our side (and we are), it seems prudent to add NULL checks here.
=> Fix crash if Sky::getSunLight returns NULL.

src/applications/osgearth_viewer/osgearth_viewer.cpp, src/osgEarthDrivers/engine_mp/MPGeometry.cpp, src/osgEarthDrivers/engine_mp/TileModelCompiler.cpp
Hey Glenn
Here are the changes merged into master. It's actually just adding a vertex buffer object to for the texture coords and switching VAOs on.
Basically you can bind and unbind vbos while a vao is bound your just kind of losing the benefit of vaos. The issues where being caused by the fact the texture coords where sharing their vbos, altering that in vao was the issue.
Previously I did have to override createVertexArrayState in MPGeometry as their weren't enough array dispatchers allocated for the other texture cord channels, but that crash seems to have disappeared.
Anyhow it runs on my mac with a GL3 context.
=> VAO support

src/osgEarth/HTTPClient.cpp, src/osgEarthDrivers/engine_mp/MPGeometry, src/osgEarthDrivers/engine_mp/MPGeometry.cpp
Hi Glenn
Remo ran into an issue I was previously having with VAO on OSX but I thought it had been fixed within osg. Turns out it hadn't
So the change to MPGeometry is required because on line 239 of MPGeometry.cpp a texture coord unit is used that wasn't part of the geometry texture arrays. This means no vertex array dispatcher was created for it so it crashes.
I feel like it should nearly always crash, but it seems fine in some cases and like I said it stopped crashing on me, but a .earth file with no layers causes it to happen still.
The fix is pretty ugly I think, but it works and I've made it only apply when VOAs are in use as no one else seems to have the issue.
I also fixed a small compiler error in HTTPClient.cpp
My topic-vao-osx branch was merged with latest master before I did …
=> Re added createVertexArrayStates fix

src/osgEarth/TraversalData, src/osgEarthUtil/Controls
Reordered parameters to match declaration order as per Linux warning finding.  No functionality change.
=> Minor linux warning fixes on g++ 4.8.4

src/osgEarth/PhongLightingEffect.cpp
Without this, the supports variable is uninitialized value and frequently will default to false in release mode when run from console.
=> PhongLightingEffect: _supported is now initialized.

src/osgEarthDrivers/gdal/ReaderWriterGDAL.cpp, src/osgEarthDrivers/mbtiles/MBTilesTileSource.cpp
We have custom modifications in our application to enhance the OSG search path with our own routines.  This patch modifies mbtiles and gdal drivers to fall back to osgDB when files can't be found, allowing our search to find the files.
=> MBTiles and GDAL drivers now use osgDB to find URLs to open.

src/osgEarthDrivers/sky_simple/SimpleSky.Sun.frag.glsl
Broken by a combination of bfdc92a9b and 9347baed4d.
=> Simple Sky: Sun alpha is now correct and no longer obscures stars.

src/osgEarthDrivers/engine_rex/GeometryPool.cpp
In the rex engine, the VAO code for OSG post 3.5.5 didn't assign the
neighbor array.
=> SharedGeometry VAO neighbor array fix

src/osgEarthSymbology/GEOS, src/osgEarthSymbology/GEOS.cpp
Replaces #848, adds support for GEOS >= 3.6.0 while preserving compatibility with older GEOS versions.
=> Add GEOS >= 3.6.0 compatibility

src/osgEarth/Profile, src/osgEarth/Profile.cpp
since upgrading to gcc 6.3.0 some plugins fail to link
because of undefined reference to `osgEarth::ProfileOptions::mergeConfig(osgEarth::Config const&)'
=> msys2: fix link error

docs/source/references/earthfile.rst
The appended patch adds the missing documentation.
=> Add documentation for earth file tag <libraries>

src/osgEarthDrivers/engine_mp/MPGeometry.cpp
Newer OSG 3.5.6 does not need this checks.
=> VAO fix for OSG 3.5.6

src/osgEarth/OverlayDecorator.cpp
We were getting a crash in a headless startup that had an incomplete setup.  The setup didn't have LD_LIBRARY_PATH set up to find REX engine.  This fixes minor crashes related to the engine not existing.
=> OverlayDecorator: Check engine for validity before dereferencing

docs/source/startup.rst
Previous link was now a 404. Went to alphapixel.com and found current link to their downloads of prebuilt OSG and 3rd party dependencies
=> Fix broken download link for AlphaPixel

CMakeLists.txt, CMakeModules/FindGLCORE.cmake, src/osgEarth/Capabilities.cpp, src/osgEarthAnnotation/AnnotationNode.cpp, src/osgEarthDrivers/engine_mp/MPGeometry.cpp, src/osgEarthFeatures/FeatureModelSource.cpp
This support Core GL3 compile on Windows. It is the same as in OSG:
http://forum.openscenegraph.org/viewtopic.php?t=13457
https://github.com/openscenegraph/OpenSceneGraph/blob/5d6322da2b84470fc0675b1c637246acb58802e9/CMakeModules/OsgMacroUtils.cmake#L214
I've testes it on Windows x64 with master branch and OSG 3.5.6 release.
About the GL3 fixes:
GL_DEPTH_BITS and GL_CLIP_PLANE0  is deprecated on GL3. And it doesn't build with core profile without this changes.
=> Windows GLCore/GL3 support and GL3 compile fixes

src/osgEarthDrivers/feature_wfs/FeatureSourceWFS.cpp
Issue: In a WFS feature model has layout defined it implicitly sets the BBOX WFS parameter, and this would override any explicitly set SQL_FILTER in the query expression property since BBOX and CQL_FILTER are mutually exclusive.
Fix: Test is whether expression (i.e. CQL_FILTER) is available before BBOX to give it priority.
=> Give CQL_FILTER priority over BBOX if both WFS parameters are set

src/osgEarthFeatures/ResampleFilter
Without "resample" as the value of the Config key, the proper driver
won't be found.
This fixes the osgearth_city demo.
=> Add resample key to ResampleFilterOptions configuration

src/osgEarthSymbology/Style, src/osgEarthSymbology/StyleSheet, src/osgEarthSymbology/Symbol
Access methods needed to UI introspection of current applied StyleSheet and Style. This allows our application to inspect current stylesheet applied to a FeatureModel. The end-user can then make changes and reload the selected FeatureModel based on an updated / edited stylesheet.
// Start layer update transaction
map_node_->getMap()->beginUpdate();
map_node_->getMap()->removeLayer(model_layer_.get());
// Create new layer with same data options
osgEarth::Features::FeatureModelSourceOptions fms_opts(model_layer_->options().driver().get());
// Update styles / stylesheet from user input
[...snip...]
osgEarth::ModelLayerOptions ml_opts(model_layer_->getName(), fms_opts);
model_layer_ = new osgEarth::ModelLayer(ml_opts);
map_node_->getMap()->addLayer(model_layer_.get());
// End layer update …
=> Added new access methods in Style and Stylesheet

src/osgEarthDrivers/kml/KML_PolyStyle.cpp
[KML_PolyStyle]
- Now getting or creating PolygonSymbol before we apply anything to avoid breaking fill if no color is specified
=> Fixing bug where fill is ignored if no color is set in PolyStyle

src/osgEarthUtil/LogDepthBuffer.VertOnly.vert.glsl
This is needed for MacOSX Core Profile. It doesn't compile the shader without this.
=> GLSL version fix

src/osgEarthAnnotation/LabelNode.cpp
Code will now look through all children and apply to the first one found.
=> Fixes assumption that the text object is the first child of Geode

src/osgEarthUtil/RTTPicker, src/osgEarthUtil/RTTPicker.cpp
This is useful in the SIMDIS SDK for preventing the drawing of labels, which improves both performance (no need to traverse) and accuracy (no dead zones).
=> RTT: setCullMask and getCullMask added.

src/osgEarth/Horizon.cpp
Profiler pointed to a define-string to std::string conversion for UDC key taking up 5% of overall CPU time in a particular massive data example.  This is a minor performance improvement with no apparent downside.
=> Horizon: Avoid constantly constructing new std::string for UDC key.

CMakeModules/OsgEarthMacroUtils.cmake
Recent change to OSG version detection broke versioning when OSG_DIR was specified by itself.  This change lets OSG_INCLUDE_DIR fall back to OSG_DIR/include.
We have build scripts that specify OSG_DIR that lets osgEarth figure out the include path etc., as per FindOSG.cmake in line 27 (preferred path for OSG is OSG_DIR).  This change lets those build scripts continue to work.  Without this, the version on first configure is empty-string, leading to bad RPATH on Linux and incorrect install location.
=> CMake: Respect OSG_DIR when searching for OSG version.

src/osgEarth/Endian, src/tests/osgEarth_tests/CMakeLists.txt, src/tests/osgEarth_tests/EndianTests.cpp, src/tests/osgEarth_tests/GeoExtentTests.cpp
Commits from yesterday broke MSVC 2010 build.  This change not only fixes MSVC 2010 but verifies behavior via unit test.
stdint.h is required for uint32_t support on MSVC 2010.  htonll and ntohll are not defined in winsock2.h for MSVC 2010 and _byteswap_uint64 can be used in their place.
Unit test verified correct operation on 64 bit systems: MSVC 2010, MSVC 2012, MSVC 2015, and Linux g++ 4.8.  I also tested it on a MSVC 2010 32 bit system.
Also includes minor typo fixes in another test.
=> Endian: MSVC 2010 support.  Unit test added for little endian systems.

CMakeModules/FindGDAL.cmake, src/osgEarth/tinyxml.cpp, src/osgEarth/tinyxml.h, src/osgEarth/tinyxmlerror.cpp, src/osgEarth/tinyxmlparser.cpp
Attempt to prevent conflicts with applications that use their own tinyxml. Also added a search path in the FindGDAL.make module.
=> Namespace tinyxml

src/osgEarth/Endian
This incorporates the changes to the original code found in
https://gist.github.com/PkmX/63dd23f28ba885be53a5. The advantage is
that the winsock library doesn't need to be linked in.
=> Use inline Windows functions in Endian

src/osgEarth/ObjectIndex
This allows objects to reliably use tagNode(this,this), then call remove() in their own destructor.  Without this, their destructor is never called, and it's much more awkward to remove references.
=> ObjectIndex now stores observer_ptr instead of ref_ptr.

src/osgEarthDrivers/earth/EarthFileSerializer2.cpp
This is very useful when embedding earth files into other files though ReaderWriter::writeNode(const osg::Node&, std::ostream&, const Options*). This allows us to have a fix setup root reference for all resources.
=> Allow a folder to be referrer

src/osgEarth/DrapeableNode
This fixes two problems:
- DrapeableNode may not be in the NodePath of a MapNode, so its update traversal never finds an initial MapNode.  setMapNode() gives users a way to configure it properly externally.
- The Map Node may change at runtime and DrapeableNode would not catch the change.
=> DrapeableNode is now a MapNodeObserver.

src/osgEarthSymbology/StyleSheet, src/osgEarthSymbology/StyleSheet.cpp
Enables applications to keep track of what style sheet was applied to which feature model layers.
=> Adds optional name property in osgEarth::Symbology::StyleSheet

src/osgEarth/Units
was erroneously commited as part of https://github.com/gwaldron/osgearth/issues/1012
=> Units: revert gcc optimizer bug fix

src/osgEarthDrivers/engine_mp/MPGeometry, src/osgEarthDrivers/engine_mp/MPGeometry.cpp, src/osgEarthDrivers/engine_rex/GeometryPool, src/osgEarthDrivers/engine_rex/GeometryPool.cpp
This fixes update API calls to createVertexArrayState  that are createVertexArrayStateImplementation from osg 3.5.9 as mentionned by my colleague in #1039
=> update API calls to createVertexArrayState

CMakeModules/FindRocksDB.cmake
Remove some unneeded flags.
Tested with RocksDB 5.9.2 on MacOSX 10.13 without any hacks. It finds the library on standard paths. It also works with CMAKE_FIND_ROOT_PATH and CMAKE_PREFIX_PATH
=> fix: FindRocksDB.cmake for MacOSX

src/osgEarth/MapCallback.cpp, src/osgEarthUtil/WMS
MapCallback::onBeginUpdate() and MapCallback::onEndUpdate() and were not invoked as expected when my_mapnode->map()->beginUpdate() and my_mapnode->map()->endUpdate() were called.
Also WMSStyle::getName() and ::getTitle() methods should be const since operation and return references are const.
Conflicts:
src/osgEarth/MapCallback.cpp
=> Handle *_BATCH_UPDATE in MapCallback::onMapModelChanged

src/osgEarthDrivers/sky_simple/SimpleSkyNode.cpp
GL_LUMINANCE is not supported for the format parameter and generates an obscure texture error in OSG when running in GL Core 3.3.  This patch uses the supported GL_RED format, then swizzles the color (supported in 3+) so the underlying moon shader doesn't need to be updated.
=> Simple Sky: Moon now draws correctly in GL3.

src/osgEarthDrivers/engine_rex/SurfaceNode.cpp, src/osgEarthDrivers/model_simple/SimpleModelSource.cpp, src/osgEarthSplat/Zone.cpp, src/osgEarthUtil/SimplePager.cpp
Hi @gwaldron,
I was trying to compile osgEarth on macOS and had issues because clang disallows mixing double an floats in std::min and std::max.
Hopefully these corrections will work even if BoundingSphere and BoundingBox are using floats
=> Fixed compilations errors on clang

src/osgEarthUtil/Controls, src/osgEarthUtil/Controls.cpp
- Removed unused osg::TextureRectangle code path and define.
- Can use an Image or a Texture in constructor.
- Added method to get the actual texture image size.  Note that getTextureWidth() returns incorrect data until texture is applied to a state, complicating logic slightly.
- Tested Texture and Image constructors with OSG 3.6 release candidate with a swizzle, allowing for callers to fix monochrome textures with a swizzle for GL 3 core profile
- Tested Image constructor with OSG 3.4.1 in compatibility profile
=> ImageControl: Now works with Texture as well as Image.

src/osgEarthSilverLining/SilverLiningAPIWrapper, src/osgEarthSilverLining/SilverLiningAPIWrapper.cpp
Expose more SilverLining functions in the API-wrapper.
This will prepare the Silverlining node kit to provide a reflection map that later can be used in the Triton node kit. (There will be a future pull request for the Triton node kit to support this feature)
=> Expose more SilverLining functions in the API-wrapper

src/osgEarthDrivers/sky_simple/SimpleSkyNode.cpp
Encountered a segfault where image might be NULL if the moon image is not found, leading to a crash in GL3 mode.  Mea culpa.
=> Simple Sky: Fix potential NULL access.

src/osgEarthDrivers/engine_mp/MPEngine.frag.glsl, src/osgEarthDrivers/engine_rex/RexEngine.frag.glsl
Another customer had another old Intel driver (this time the 20.15.xx family), which could only handle 3 pragma parameters at a time
=> Reduced pragma length in two more shader files, for old Intel drivers.

src/osgEarth/Capabilities, src/osgEarth/Capabilities.cpp, src/osgEarthDrivers/sky_simple/SimpleSkyNode.cpp
Also fixed a problem with star point sprites.  They are required past GL3 if in compatibility mode (i.e. not in core mode)
=> Capabilities: Detect core profile support added.

src/osgEarth/LineDrawable
Typename isn't required here because it's not ambiguous whether "T" is being used as a type or not (it definitely is).  GCC doesn't like superfluous typename, whereas MSVC is happy to ignore them.
=> LineDrawable: GCC compile fix

src/osgEarth/Text.frag.glsl
For reference: https://github.com/openscenegraph/OpenSceneGraph/commit/05af4340e1c3
This helps with 3.6 OSG providing more crisp text at smaller font sizes.
=> Text: Import OSG changes to Text shader for alpha saturation.

src/osgEarth/GeoData, src/osgEarth/GeoData.cpp, src/osgEarthUtil/TMS.cpp
adds an optional string property "description" to DataExtent. This allows to add a human readable description to each data extent in tms.xml, since the coordinates are quite confusion sometimes.
=> add description to DataExtent

src/osgEarth/Text.frag.glsl
Referring to osg f61213f says more than 3 will crash intel drivers
=> Split #pragma import_defines to 3 per line

src/osgEarthSilverLining/SilverLiningContext.cpp, src/osgEarthSilverLining/SilverLiningSkyDrawable.cpp
This was more straightforward than fixing Triton (maybe due to better familiarity with API Trace).  Swaps out the renderer based on FFP availability, and fixes a problem where osg State is confused after Triton draws the sky.
=> SilverLining: Support GL Core 3.3 builds.

src/osgEarthTriton/TritonAPIWrapper, src/osgEarthTriton/TritonAPIWrapper.cpp
With this PR you can set the Triton environment map through the API-wrapper. This way you can  transfer a environment map generated by Silverlining to Trition.
=> Expose more Triton functions in the API-wrapper

src/osgEarthTriton/TritonAPIWrapper.cpp
On Windows, TextureHandle is a pointer and a reinterpret_cast<> is appropriate.  On Linux, it's an int, and at least on g++ 4.4 it's illegal to reinterpret_cast<> a size_t to an int.  Similarly, it's illegal to reinterpret_cast<> an int to a size_t.
An alternate fix should be to use static_cast<> on Linux (based on `if _WIN32`) and use the preprocessor, but that looked more messy than just having a C-style cast.
=> Triton: Fix Linux compile error with reinterpret_cast on g++ 4.4

src/osgEarthUtil/Controls.cpp
Tested on both OSG 3.4 and OSG 3.6 using Image Controls and Label Controls.
=> Controls: Image and Text fixed for OSG 3.4

src/osgEarthAnnotation/PlaceNode.cpp
Cleanup glCompileShader error:
VERTEX glCompileShader "oe_PlaceNode_icon_VS" FAILED
VERTEX Shader "oe_PlaceNode_icon_VS" infolog:
0(5) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140
=> fix glCompileShader error with placenode

src/osgEarthQt/LayerManagerWidget.cpp, src/osgEarthQt/MapCatalogWidget.cpp
The calling sites in osgEarthQt for getOrCreateNode have been updated to getNode.
=> osgEarthQt: ModelLayer::getOrCreateNode was changed to ModelLayer::getNode.

docs/source/references/symbology.rst
Per OSG docs ( https://github.com/openscenegraph/OpenSceneGraph/blob/master/include/osgText/Text#L89 ) this value is in units of percentage, not pixels.
=> Corrects units of text-halo-offset and friends.

src/osgEarthQt/ViewerWidget.cpp
I am using ViewerWidget to display osgEarth content on Linux using an Intel GPU with Core Profile (GPU supports OpenGL 4.5).
I have set the context version using:
osg::DisplaySettings::instance()->setGLContextVersion("4.5");
However this was not being honored when the ViewerWidget was created, thus resulting in a non Core Profile OpenGL context being created by Qt. The result was a bunch of GLSL compile errors.
This update sets the OpenGL version that Qt is to use. This results in the earth being visible.
=> Update Qt OpenGL context to use the version of OpenGL requested via the Qt graphics context setup.

src/osgEarth/PrimitiveIntersector.cpp
This was discovered when using old style picking. Occasionally drawable would be null.
=> nullptr test added for the drawable parameter on entry to PrimitiveItersector::intersect

src/osgEarth/GeometryClamper
Tested on g++ 4.4, g++ 4.7, and MSVC 2015
=> GeometryClamper: g++ 4.4 build error fix.

src/osgEarth/Containers
Noticed issues with LRUCache docs.  Looks like put() was replaced by insert(), and get() signature changed.
=> LRUCache: API documentation update.

src/osgEarthUtil/MGRSGraticule.cpp
Tested on g++ 4.4.  We've seen this in the past.  MSVC treats long as int, 32 bits.  g++ x64 4.x treats it as a 64 bit long integer.  Easily fixed by swapping to int, which both respect as 32 bits.
I did not update `OE_ENCODE_LONG` which works just fine and presumes 32 bits.
=> MGRSGraticule: Fix binary data read on Linux.  unsigned long is 64 bits, not 32, on g++ 4.x x64

src/osgEarth/DrapingTechnique.cpp
This fixes draping after OSG commit 86bd4 which enabled glTexStorage,
=> change GL_RGBA to GL_RGBA8 to work with glTexStorage

src/osgEarth/Text.frag.glsl
osgEarth VP does not need this.
=> Text fragment shader: remove unused lines

src/osgEarthTriton/Shaders/user-functions.glsl, src/osgEarthTriton/Shaders/user-vert-functions.glsl
Note that this requires https://github.com/gwaldron/osgearth/pull/1185 or the ocean will show up transparent in Triton 4.x, due to default uniform value of 1.0.
=> Triton Shaders: Add ocean alpha; add support for older GLSL.

src/osgEarthSymbology/GEOS
According to the 3.7.0 release notes, the C++ API changed, resulting in a compilation error:
osgearth/src/osgEarthSymbology/GEOS:51:38: error: ‘unique_ptr’ in ‘class geos::geom::GeometryFactory’ does not name a type.
Instead, use geos::geom::GeometryFactory::Ptr which should be compatible with Geos 3.6 as well.
=> Fix compilation error with Geos 3.7.0.

src/osgEarthUtil/GeodeticGraticule.cpp
Without this, the define OE_DISABLE_GRATICULE is not configured properly.
=> Geodetic Graticule: Grid line visibility from Options is now respected.

src/osgEarthUtil/GraticuleLabelingEngine, src/osgEarthUtil/GraticuleLabelingEngine.cpp, src/osgEarthUtil/MGRSGraticule.cpp
The styles are named xedge and yedge.
=> MGRS: X and Y edge labels can now be styled.  Fixed crash bug in UpdateLabelStyles on label iteration.

src/osgEarth/GeometryClamper.cpp, src/osgEarthUtil/ClampCallback.cpp
Allow building with the OSG cmake flag, OSG_USE_DEPRECATED_API since osg::Geometry::dirtyDisplayLists is removed with this option enabled starting with OSG 3.6.0.
=> Fix build with deprecated build flag

src/osgEarthUtil/RTTPicker.cpp
This makes sure we don't read at _offsetX==w nor at _offsetY==h in
SpiralIterator::next(), which would give garbage results.
This fixes #1250.
=> Fix bounds checking in RTTPicker::pick

src/osgEarthDrivers/sky_simple/SimpleSky.Moon.frag.glsl
gl_FragColor was deprecated, then removed.
=> Moon: Shader now builds under GLSL 3.3

src/osgEarth/Lighting.cpp
This line was missing and caused some weird color issues for models using Material only. The wrong previous color from other models "leaked" into neighboring models. Occurs when building with GLCORE profile.
=> Apply the diffuseFront color to the state; same as osg::Material::apply

src/osgEarth/Config.cpp
`Config:: _refMap` is lost when doing `Config::merge`. I find this issue when running `osgearth_features` demo with `--mem` option.
=> Fix Config:: _refMap lost when doing Config::merge

docs/source/about.rst
Apologies for the .rst linting noise from removing non-functional whitespace. Also assuming you would want to promote your other social media sites now that Google+ is defunct.
=> Corrects missing / broken URLS in documentation.

src/osgEarth/LayerShader
This patch is required to compile osgearth on Windows.
=> Windows compile fix

docs/source/references/symbology.rst, src/osgEarthFeatures/CMakeLists.txt, src/osgEarthFeatures/FirstVertexFilter, src/osgEarthFeatures/FirstVertexFilter.cpp, src/osgEarthFeatures/GeometryCompiler.cpp, src/osgEarthSymbology/InstanceSymbol, src/osgEarthSymbology/InstanceSymbol.cpp, src/osgEarthSymbology/MarkerSymbol, src/osgEarthSymbology/MarkerSymbol.cpp, src/osgEarthSymbology/ModelSymbol.cpp
Documentation added by Ralf Habacker.
We needed this for a project and want to share this. 
We are using the 2.8 branch, because the last stable branch 2.10 has issues with virtual box clients (GLES 3.3 required)
=> Add PLACEMENT_FIRSTVERTEX option for ModelSymbol on line geometries

docs/source/about.rst
there's not top level domain .osg (yet)
ps. The google+ page link under social media (pelicanmapping?) seems dead to me. As I can't find pelicanmapping on google+ I think it should be removed.
Regards, Laurens.
=> documentation typo fix in link to forum.osgearth.osg; 

src/osgEarth/Tessellator.cpp
Bugfix for the earcut tessellator #1341. It checks the polygons in which plane it is.
=> fix for earcut tessellator 

src/osgEarthUtil/RTTPicker.cpp
Picking with cascaded draping doesn't work on first hit, because the picker hasn't enough frames?
I can't reproduce it after this fix. But is it correct?
=> Picking with cascaded draping needs 4 frames?

src/osgEarthDrivers/gltf/GLTFReader.h
Seeing this on g++ 8.3, but not on g++ 4.8.5.
=> GLTF: Fix g++ 8.3 compile issue with extra qualification.

src/osgEarth/PointDrawable, src/osgEarth/PointDrawable.cpp
Unlike `LineDrawable`, `PointDrawable::insert()` is pretty simple to support.  We insert points into an ordered vector for code that we use that currently uses `GL_POINTS`, that we're trying to upgrade to `PointDrawable`.  Having access to an `insert()` method helps us avoid accessing the internals of `PointDrawable` directly to get done what we need to do.
=> PointDrawable: New insert() method.

src/osgEarth/PointDrawable.glsl
I was setting alpha on some points and it wasn't being respected, tracked it down to this.
Note the same problem occurs on master, but master is using what looks like a more up-to-date PointDrawable.glsl that looks improved for compatibility.  Might want to cherrypick that change from master too?
=> PointDrawable: Respect incoming alpha value.

src/osgEarthDrivers/kml/KML_Geometry.cpp
If a comment is found while parsing the coordinate list in the rapidxml.hpp, the coords found after the comment are all added as another child node, but the m_value field string only reflects the first node. Instead, iterate through all of the coordinate node's child nodes to make sure all coordinates are parsed.
=> KML_Geometry parseCoords ensures all coords are parsed in case of comment in the coord list

src/osgEarth/Containers
Fixes a compile error seen on MSVC 2015.  2017 and 2019 are happy with original, so is gcc 8.3.
=> Containers: MSVC 2015 compile fix

src/osgEarth/PrimitiveIntersector, src/osgEarth/PrimitiveIntersector.cpp
The copy constructor for PrimitiveIntersector::Intersection was defined in
the cpp file while the rest of the struct was defined inline in the
header.  This meant that you couldn't copy the struct without from your
own project without getting linker errors.  I simply moved the copy ctor
to be inline like the rest of the struct.
=> Moved PrimiveIntersector::Intersection copy constructor

src/osgEarthDrivers/gltf/GLTFWriter.h
Cesium may crash if using texture without texCoords
=> ignore material/texure if there is no texCoords in GLTFWriter

src/osgEarth/GeoPositionNode
I realize that this is somewhat meaningless update, but I copied this class into my 2.7 build of osgEarth and later ran into problems because the header guard is the same as the one defined in OrthoNode, which no longer exists in 3.0.  Still, I figured I'd go ahead and fix it since I spotted it.
=> Fixed the header guard in GeoPositionNode

src/osgEarthDrivers/gltf/GLTFWriter.h
when stateSet's GL_BLEND is ON, set GLTF alphaMode to "BLEND"
=> simple support of AlphaBlend material in GLTFWriter

src/osgEarthDrivers/gltf/GLTFWriter.h
GLTF doesn't accept CLAMP_TO_BORDER so use CLAMP_TO_EDGE instead
=> convert CLAMP_TO_BORDER to CLAMP_TO_EDGE in GLTFWriter

src/osgEarth/TerrainTileModelFactory, src/osgEarth/TerrainTileModelFactory.cpp
Add locking around generateMipmaps() call for images that might be
coming from a cache. It's impossible to atomically check if an Image
has a mipmap already, so this code always locks.
resolves gwaldron/osgearth#1502.
=> TerrainTileModelFactory mutex

src/osgEarth/ElevationPool.cpp
Ternary operator did not want to use the to-int operator automatically.  Delete did not want to delete a `void*` pointer.
=> ElevationPool: Fix Linux g++ 8.3 build errors.

docs/source/data.rst
'Take **is** a step further' -> 'Take **it** a step further'
=> Fixing a typo

src/osgEarth/FileUtils.cpp
I am using GDALDEM driver, which is getting lots of errors on the console about various TIF files already existing or not existing.  This has led to crashes at runtime.  This change works around that problem by encoding the thread ID into the temporary filename, which helps prevent multi-threaded failures.  As a result, GDALDEM no longer crashes sporadically and I haven't seen any filename errors yet.
=> FileUtils: getTempName() adds thread ID, making it more robust while threading

src/osgEarth/GDALDEM, src/osgEarth/GDALDEM.cpp
Have been using `GDALDEM` and ran into several issues that this PR fixes:
* `altitude` option and text appears to be taken already by `ImageLayer::Options::altitude()`.  Renamed to `get/setLightAltitude()` (`light_altitude`) in order to not hide the base class value
* Added 'alpha' option, which is useful on color-relief images
* Added various documentation on the options, since many were not obvious in their intent or usage
* Setting the elevation layer now reopens the layer if needed
* Added implementation for various get/set functions, which were declared but not implemented.
* Fixed return values on `getMultidirectional()` and `getCombined()`
=> GDALDEM: Clean-up, fix missing functions, add alpha option, rename altitude to lightAltitude.

src/osgEarth/TDTiles
fix a spell error in src/osgEarth/TDTiles in line 223, from `Tileet` to `Tileset`
=> fix a spell error in src/osgEarth/TDTiles in line 223, from `Tileet` to `Tileset`

src/osgEarthDrivers/gltf/GLTFReader.h
src/osgEarthDrivers/gltf/GLTFReader.h include same header `#include <osgDB/FileNameUtils>` twice
=> src/osgEarthDrivers/gltf/GLTFReader.h include same header `#include <osgDB/FileNameUtils>` twice

src/osgEarth/ElevationPool.cpp
`ElevationPool::getSample()` provides a signature that omits the maximum LOD parameter.  In this case, it is fed in as `~0`, which is of type `unsigned`.  This function gets it, and on old line 761 typecasts it to an `int` so that `osg::minimum()` can be used.  But that typecast results in a negative number, making `lod` always be `-1` when coming from that other signature.
This fixes that problem by limiting the incoming `maxLOD` value to, at most, `std::numeric_limits<int>::max()`.
=> ElevationPool: Fix overflow error in getSample().

src/osgEarthDrivers/engine_rex/GeometryPool.cpp
Added setting of VBO usage flag in VertexArrayState prior to drawing in SharedGeometry::drawImplementation() because sometimes (at least on Windows) the OSG StatsHandler would change this VBO usage flag to false prior to SharedGeometry::drawImplementation() being called.  This would cause the VBO to not be bound when glDrawElements was called and resulted in crashes.
=> Added setting of VertexArrayState VBO usage flag to ensure VBO is bound if necessary

src/osgEarth/GeodeticGraticule
Please append "OSGEARTH_EXPORT" to the declaration of struct "CameraData". Otherwise,  "CameraData::~CameraData()" won't be found when building "osgearth_geodetic_graticule.exe".
=> Exposing struct "CameraData" to dll

src/osgEarth/Async, src/osgEarth/BrightnessContrastColorFilter.cpp, src/osgEarth/CMYKColorFilter.cpp, src/osgEarth/ChromaKeyColorFilter.cpp, src/osgEarth/GLSLColorFilter.cpp, src/osgEarth/GammaColorFilter.cpp, src/osgEarth/HSLColorFilter.cpp, src/osgEarth/MapNodeObserver.cpp, src/osgEarth/NightColorFilter.cpp, src/osgEarth/RGBColorFilter.cpp, src/osgEarthDrivers/cache_leveldb/LevelDBCache.cpp, src/osgEarthDrivers/cache_leveldb/Tracker, src/osgEarthDrivers/cache_rocksdb/RocksDBCache.cpp, src/osgEarthDrivers/cache_rocksdb/Tracker, src/osgEarthDrivers/engine_mp/GeometryPool, src/osgEarthDrivers/engine_mp/HeightFieldCache, src/osgEarthDrivers/engine_mp/MPTerrainEngineNode, src/osgEarthDrivers/engine_mp/TileGroup, src/osgEarthDrivers/engine_mp/TileNodeRegistry, src/osgEarthDrivers/engine_mp/TilePagedLOD, src/osgEarthDrivers/ocean_simple/ElevationProxyImageLayer, src/osgEarthDrivers/ocean_triton/TritonDriver.cpp
to osgEarth/Threading due to ThreadingUtils no longer existing in version 3.0. osgEarth/Threading seems to be included in several lower level includes so its possible these lines can be removed completely.
=> Changed include references from osgEarth/ThreadingUtils

src/osgEarthDrivers/earth/EarthFileSerializer2.cpp
For example, field names uri and url were converted for relative path, but field names like texture_uri and cursor_url were not converted.  This led to saved earth files not being able to be loaded properly in some conditions.
This change basically expands the definition of which fields will be processed for URL handling for rewriting paths as relative, so more field names will be included.
=> Earth Serializer: Apply relative path now also to fields containing underscores

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/test/linux-vcpkg.yml, .github/workflows/windows.yml
Add github actions to build osgEarth 3.1 on windows, linux and macos. "vcpkg" only works with windows. using xcode 12 on macos. I've tested it on my osgEarth 3.1 branch. All builds successed, but one need to test/adapt it for osgEarth repository.
All action have "workflow_dispatch". To build it on push, one can change this to "push". 
Attention: The "windows action" use "vcpkg" and creates "nuget" packages on your current github account!
=> 3.1: github actions for windows, linux and macos

src/osgEarth/Threading, src/osgEarth/Threading.cpp
Using this in a client application to determine if there are asynchronous jobs running for the terrain paging.  Previously we were relying on output from the Registry's activities, but asynchronous layers don't show up there.  The easy solution for us was to query both the Registry activities, and to also query whether there are queued async jobs.  Combined, this looks good on our end user app.
=> JobArena: Add queueSize() public method.

docs/source/data.md
Just a one-char typo I noticed while reading the docs:  was --> has
=> Fix typo in data.md

src/osgEarth/ExampleResources
It doesn't have a default template for this enum.
=> fix: MacOSX build issue with ExampleResources

src/osgEarth/Threading.cpp
`maxArenaIndex` stores the maximum index, e.g. `7` for an array of 8 arenas.  There was an off-by-one issue that was causing asynchronously loading layers to not be counted because they were the last in my list of arenas.  I also spotted a minor type in `totalJobsRunning()`.
=> Threading: Fix metrics off-by-one count, fix totalJobsRunning call.

src/osgEarth/DrapingTechnique
gcc (sometimes?) requires declaration of the class prior to friend declaration.  MSVC lets the friend declaration also declare the class.  This fixes the build for me on GCC 8.3.1.
=> DrapingTechnique: Forward declare friend MapNode.

src/osgEarth/WMS.cpp
Was getting a crash with a WMS server that reported ESPG:26915 SRS, and my system returns nullptr when trying to create.  This patch avoids a `nullptr` dereference on `wms_srs` in the lower portion, that was crashing the application.
Afterwards I was still getting a soft assert in Profile::create() due to the null SRS.  I protected against that too.
=> WMS: Avoid nullptr dereference on wms_srs.  Avoid soft assert on Profile::create() with nullptr srs

docs/source/build.md
The instructions say to install the optional dependency `webp:x64-windows` which throws the error:
```
Error: while loading web:
The port directory (C:\src\vcpkg\ports\webp) does not exist
Error: failed to load port from C:\src\vcpkg\ports\webp
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
Changing the package name to `libwebp:x64-windows` removes the error.  Was the package name changed recently?  I'm not certain that this is the correct fix, so someone in-the-know should verify that it is.
=> Change webp -> libwebp in build.md

src/osgEarth/Tessellator.cpp
This fixes a crash when creating a degenerate `osgEarth::Polygon` in debug mode MSVC 2019.  The LLA coordinates of such a degenerate shape are (11,11), (10,10), (11,11).  Note the duplicate point.  The crash occurs a few lines below on 231 when `plane` is accessed, possibly uninitialized.
=> Tessellator: Fix possible access of uninitialized value.

src/osgEarth/Threading
On MSVC 2019 and release mode MSVC 2017, the `atomic<int>` was initializing to 0 as the code expects already.  But on debug MSVC 2017, I was seeing random values.  This meant that the metrics were not starting at 0, and therefore not useful.  This fixes that problem.
=> Threading: Initialize atomic<int> values to 0 in constructor.

src/osgEarth/rtree.h
Quick syntax fix complained on by g++ 8.3
=> rtree: Fix typename for gcc build.

.github/workflows/macos.yml, src/osgEarthDrivers/gltf/ReaderWriterGLTF.cpp, src/third_party/tinygltf/tiny_gltf.h
This is the simplest fix to build the current integrated version of tinygltf with MacOS/XCode. Future fixes need to port tinygltf to >=2.5
=> fix build issue with tinygltf on MacOS/XCode

src/osgEarth/GEOS.cpp, src/osgEarth/Geometry.cpp
This is a fix of how to create a pointset using GEOS.
Problem: GEOS::importGeometry is failling when creating a pointset  using GEOSGeom_createPoint_r. this fonction can create only one point and fail if you give more than one!
=> fix second GEOS issue with Pointset ( issue #1691 )

src/applications/osgearth_collecttriangles/osgearth_collecttriangles.cpp
Fixes an error when building x64 Linux with gcc 8.3:
```
/usr/people/github/osgearth/src/applications/osgearth_collecttriangles/osgearth_collecttriangles.cpp:212:65: error: cast from ‘osg::Drawable*’ to ‘unsigned int’ loses precision [-fpermissive]
Random prng(reinterpret_cast<unsigned int>(&drawable));
```
=> Collect Triangles: Fix 64-bit Linux compile error with downcast.

.github/workflows/windows.yml
Update windows github action to fix #1761 
vcpkg update: 2020.11 > d417ae59d6e9aa20d9f812b5deb966645c54687d
=> fix: github actions - windows

src/osgEarth/LineDrawable.cpp
We have seen issues in our code where lines are no longer updating properly after the 7/15 update in https://github.com/gwaldron/osgearth/commit/0be4fb979
We thought we were missing calls to ``dirty()``, but I investigated today when we encountered similar issues with lines drawn from the Callouts technique in screen space layout code. I found the underlying issue in a missing data variance on the geometry.
After this change, callout lines updated properly. I suspect this fixes all of our various line drawable issues.
=> LineDrawable: Fix data variance on contained geometry.

src/osgEarth/WMS, src/osgEarth/WMS.cpp
I have a WMS server that I'm connecting to that has over 6000 reported supported SRS in a parent layer, with more than 600 layers under it. I'm seeing a 30 second delay to load the layer due to SRS processing. This change reduces the load time by an order of magnitude by eliminating an n^2 loop that was preventing duplicate entries. std::set now forces uniqueness.
=> WMS: Change structure to a set to avoid an O(n^2) SRS lookup loop.

src/osgEarth/Config, src/osgEarth/Layer
For example, `OE_OPTION` can only be used if in osgEarth namespace, or if `using` is added to a header file. Same with `META_LayerOptions`. This fixes a compilation issue in third party code introduced by https://github.com/gwaldron/osgearth/commit/06925204e9d8266382d924d3a6732df654e1893b
=> Explicit namespaces added to macros to allow them to be used in derived non-osgEarth classes.

src/osgEarthDrivers/engine_rex/TileNode, src/osgEarthDrivers/engine_rex/Unloader.cpp
Basically, during an update traversal, UnloaderGroup is going through its dead pool, after collecting dormant tiles. As it looks through the dead pool, it pulls out a tile’s parent. This is a naked pointer inside the TileNode. The parent appears to have been deleted already. Several fields are 0xdddddddd. The tile itself seems OK and valid, it’s just the parent tile that appears invalid.
I have not had success reproducing this in osgEarth examples. The crash happens during the update traversal through UnloaderGroup.
=> TileNode: Fix naked pointer that can be dereferenced after deletion during UnloaderGroup dormant tile collection.

src/osgEarth/TiledFeatureModelGraph.cpp
Fixes crash bug encountered when loading an older earth file that had tags for VTPKFeatures and TiledFeatureModel.
=> TiledFeatureModelGraph: Fix crash on null access

src/osgEarth/Units
Found while building with GCC 11 with the -std=c++20 flag turned on. Will cause compilation to fail, and the template on the constructor is unnecessary.
=> Units: remove unneeded template on qualified_double constructor

src/osgEarth/ImageUtils.cpp
Fix for issues found stemming from [f551c75](https://github.com/gwaldron/osgearth/commit/f551c750acbc740fa83c3bbdc037a6705cea0dca?diff=split). `GLTypeTraits<>::scale()` all return double. Float conversion issues are causing artifacts near edges, preventing some pixel-testing from working, which we use for transparent image guessing.
=> ImageUtils::ColorWriter float/double mixup

src/osgEarth/LineDrawable.glsl
https://github.com/gwaldron/osgearth/commit/20c407341 reintroduced a drastic graphical distortion in some `LineDrawable` instances drawn in 3D at an angle. These lines did not contain stipple. This change backs out the change in that commit, while keeping the quantize behavior that was added.
=> LineDrawable: Reverted part of 20c407341 that caused significant graphical distortion

src/osgEarth/ArcGISTilePackage.cpp
`osgEarth::getFullPath()` behaves differently when absolute paths are passed into the second parameter. This removes the leading slash, which is used to indicate absolute path on Linux, fixing display of ArcGIS Tile Packages on Linux.
=> ArcGISTilePackage: Remove extraneous slash that caused ArcGIS Tile Package to fail under Linux

osgEarthConfig.cmake.in
The osgEarthConfig.cmake.in file does not create an `osgEarth` target, which causes configuration to fail in CMake upon calling `set_target_properties(osgearth ...)` on a nonexistent target here: https://github.com/gwaldron/osgearth/blob/218e23fb7fee6443dcfeec3d60f0d2c79dbbedde/osgEarthConfig.cmake.in#L41
---
In addition, I believe the variable and target names are not capitalized correctly. As defined in src/osgEarth/CMakeLists.txt, the library name is "osgEarth".
https://github.com/gwaldron/osgearth/blob/218e23fb7fee6443dcfeec3d60f0d2c79dbbedde/src/osgEarth/CMakeLists.txt#L53
However, all variable and target names in osgEarthConfig.cmake.in use the lowercase "osgearth", which can result in unexpected behavior or configuration errors. With standard variables such as …
=> Fix target names in osgEarthConfig.cmake.in

src/osgEarth/ImGui/LayersGUI, src/osgEarth/ImGui/NetworkMonitorGUI, src/osgEarth/ImGui/TerrainEditGUI
We are receiving reports that SIMDIS SDK (building against osgEarth) is failing to build on a C++11 compiler. Though RHEL-7's native gcc 4.8.5 isn't exactly C++11, it is close. After this set of changes in osgEarth and a few other changes in SIMDIS SDK, we can get a successful build.
=> ImGui: Build fixes against gcc 4.8.5

src/osgEarth/EarthManipulator, src/osgEarth/EarthManipulator.cpp
Touch improvements on `EarthManipulator`, including:
* `Settings` gets new `bindTouchDrag()`, defaulting to `ACTION_PAN`. New `EVENT_TOUCH_DRAG` to support this.
* Single touch now uses the new `EVENT_TOUCH_DRAG` instead of `EVENT_MOUSE_DRAG` from left mouse
* Multi-touch now works with 2 or more fingers, rather than just 2 fingers, ensuring that single touch/drag only ever gets a single finger.
This is most useful in cases where the `EarthManipulator` settings for left click/drag are different from what you'd want in the touch/drag case. This is the case with SIMDIS SDK, where we change the default left drag operation but doing so makes touch operations basically unusable.
This does introduce a new enum and public method, and I recommend an osgEarth API version update if/when this is …
=> EarthManipulator: Decouple Pen/Touch Drag from Left Mouse Drag

src/osgEarth/ShaderUtils.cpp
Uncommented code block that was commented out in 86a72d202. By commenting this out, SIMDIS SDK's capability to accept multiple projectors on a single entity is broken. By uncommenting it, the functionality is fixed again. It looks like this might have been commented out temporarily / accidentally in that changeset to test the impacts of other fixes in the code.
=> ShaderUtils: _uniformAlt now properly added into state set

src/osgEarth/EarthManipulator.cpp
Multi-touch processes touch events into the `TouchEvents` vector, which then (previously) skipped the is-tether-action check. Now we skip the early tether check on multi-touch, and later on check the `TouchEvents` to see if they match. Tested against SIMDIS SDK with tethered insets, watching tether break for a pan event but not a rotate event.
=> EarthManipulator: Multi-touch can now clear tether

src/applications/osgearth_conv/osgearth_conv.cpp
While processing very large files I found that the progress report with just minutes and seconds was a bit hard to read, so I updated it with days and hours as well.
It always outputs days and hours even if it's not needed. This can be fixed, but leads to more code. Please let me know what you want.
=> Update osgearth_conv progress report

src/osgEarth/GeoData.cpp
Avoids a null access on SRS that can be triggered with the following code block:
```
osgEarth::Style style;
auto label = new osgEarth::LabelNode("crash", style);
```
Introduced in https://github.com/gwaldron/osgearth/commit/9454d221
=> GeoPoint: Avoid null access on SRS

src/osgEarth/Config, src/osgEarth/DateTime, src/osgEarth/SpatialReference, src/osgEarth/Threading
Fixed type comparison issue and order of initialization warnings in headers, noticed when building software against installed osgEarth. No functionality changes intended.
=> Fixed minor Linux issues in header files that impact end user projects

src/osgEarth/ImGui/AnnotationsGUI
Getting build errors when including this in other code. Appears to be missing `osgEarth::` namespace, due to being in anon namespace without a `using` statement.
=> AnnotationsGUI: Fix namespace errors

src/osgEarthDrivers/engine_rex/DrawState.cpp
If one of the programs (e.g. HexTiler) fails to compile, it's possible to get `_pcp` as null. This patch fixes the immediate crash from that behavior. The globe still isn't shown in that case, but at least the software doesn't segfault immediately.
I know this is an unexpected case of null `_pcp`. I'd rather fix the root cause but since it looks like this can happen from a bad glsl, it might be easily triggered, so there should be some protection. I'm still looking for/at the root cause in the shader, it's something in the new Hex Tile stuff.
=> Rex DrawState: Fix crash from accessing possible null.

src/osgEarth/TileMesher.cpp, src/osgEarth/rtree.h
Using `[&]` is not going to be supported as a default parameter for a function. Bounding box can take a const reference, but not a non-const reference. These two fix #2345 also.
=> Linux: Fixed syntax errors in build

src/osgEarth/ImGui/AnnotationsGUI
After fixing my local issue with getting GEOS linking (which I was able to fix in my own internal configuration), I started to get build errors with my own code that was including ImGui/AnnotationsGUI. These fixes allow the code to continue to compile on CentOS 7.9, gcc 11.2.1. Note that this compiles fine inside osgEarth and is only a problem in code that uses osgEarth as a third party library.
AnnotationNode include is required because of a dynamic_cast in the file needing to know how to cast; forward declare is insufficient. Namespace declarations required because external code does not include `using namespace osgEarth; using namespace osgEarth::Util;` like some of the osgEarth examples.
=> AnnotationsGUI: Namespace issues, fix missing include for dynamic_cast

src/osgEarth/Chonk, src/osgEarth/ImGui/AnnotationsGUI, src/osgEarth/NodeUtils
Fixed compile bugs seen on Linux side:
* `ChonkDrawable` is now forward declared. Previously it was mentioned below in a `friend class ChonkDrawable` but gcc doesn't treat that the same as a `class ChonkDrawable` declaration, though MSVC accepts it.
* Lambdas are now passed by const reference instead of non-const reference. The Lambda gets copied anyways, so const is fine, and allows for r-values. MSVC also lets you get away without the const but probably shouldn't.
No functionality changes, just compiler fixes.
=> Chonk, NodeUtils: Fixed Linux gcc compile bugs

src/osgEarthCesium/PrepareRenderResources.cpp
This adds a simple GLTF baseColorFactor support and fix a case when "baseColorTexture" is not initialized.
I understand that the GLTF osgEarth parser requires a new PBR shader to fully support all potential materials. However, this simple modification enables the display of colors in certain 3DTiles layers.
=> cesium-native: add a simple GLTF "baseColorFactor" support

CMakeModules/FindDraco.cmake
This fixes a failure on Linux on CMake 3.23.2. I'm not sure why this is not failing on other systems.
=> Draco: Fix CMake 3.23.2 configure error with unknown select_library_configurations macro

src/osgEarthDrivers/engine_rex/RexEngine.ImageLayer.glsl, src/osgEarthDrivers/engine_rex/RexEngine.vert.glsl, src/osgEarthDrivers/engine_rex/RexTerrainEngineNode.cpp
Reduced the mesa issue to a single line workaround
Ref: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10482
=> Simpler mesa 22.1.x bug workaround

src/osgEarth/ImGui/EnvironmentGUI
ImGui Environment window is no longer always shown, and now respects the window Close button. This was introduced on 10-23 in 2c78d941 in a fix that lets users install the sky if it isn't installed yet.
I made sure that you can still actually install the sky using the GUI if it wasn't yet installed.
Without this change, the Environment Sky GUI pops up in at start-up of several SIMDIS SDK examples where there are sky nodes. Pressing the "X" button in the top-right doesn't do anything. This change fixes that problem.
=> Sky GUI: Window No Longer Always Visible

src/osgEarth/GeometryUtils, src/osgEarth/GeometryUtils.cpp, src/osgEarth/OgrUtils.cpp
This commit allows:
1) Reset OGR geometries order to standard order.
2) Add geometryToIsoWKT function. (the geometryFromWKT is capable to read both wkt and isoWkt).
I have tested point, line, polygon geometries and are still loading correctly.
=> Reset OGR order to standard;

src/osgEarth/CMakeLists.txt
Fixes linker error on my Linux system where meshoptimizer library was not found.
=> Mesh Optimizer: No longer link in if not found

src/osgEarth/PBRMaterial.cpp
While Windows was happy to convert the `osg::Image*` to a `ref_ptr<osg::Image>` and construct a `Result` from that, gcc was unhappy. Explicitly constructing the `ref_ptr` fixes the issue.
=> PBRMaterial: Fix Linux constructor build error

src/osgEarth/weejobs.h
Fixes compile error `error: standard attributes in middle of decl-specifiers` on gcc
=> weejobs: Fix location of WEEJOBS_NO_DISCARD for gcc

src/osgEarthDrivers/engine_rex/RexTerrainEngineNode.cpp
=> Fix: Shared Image Layer Samples are not pruned when layer is removed

src/applications/osgearth_collecttriangles/osgearth_collecttriangles.cpp, src/applications/osgearth_windows/CMakeLists.txt, src/applications/osgearth_windows/osgearth_windows.cpp
I was getting build errors in my Windows configuration without these fixes. Looks like they might have been overlooked during a recent refactor.
=> Apps: Fixed ImGui for Windows and CollectTriangles apps

src/osgEarth/Capabilities.cpp
This was introduced in a recent refactor. Not sure how Windows is working here, as the "Version" file is in the build directory at `build_dir/build_include/osgEarth/Version`
Another fix is to update this back to `"osgEarth/Version"`. I suspect that removing this works simply because one of the other headers already includes it, but removing the header was a clean fix that compiled cleanly for me too.
Without a change here, Linux builds are continuing to fail. Again, unsure how Windows is apparently working.
=> Capabilities: Remove unused Version include that does not compile

src/osgEarthCesium/CesiumCreditsNode, src/osgEarthCesium/CesiumCreditsNode.cpp, src/osgEarthCesium/CesiumIon, src/osgEarthCesium/CesiumIon.cpp, src/osgEarthCesium/CesiumLayer, src/osgEarthCesium/CesiumLayer.cpp, src/osgEarthCesium/CesiumTilesetNode, src/osgEarthCesium/CesiumTilesetNode.cpp, src/osgEarthCesium/Context, src/osgEarthCesium/Context.cpp, src/osgEarthCesium/Settings.cpp
This support Cesium Ion self-hosted. Tested with "single-user" mode. Use 'server' property in CesiumNative3DTiles to activate this. 
Example:
```xml
<CesiumNative3DTiles name="own dataset" >		
<asset_id>1</asset_id>
<server>https://api.example.ion/</server>
</CesiumNative3DTiles>
```
implementation for this: https://github.com/gwaldron/osgearth/issues/2613
=> osgEarthCesium: support of Cesium Ion self-hosted

src/osgEarth/ShaderGenerator
Fixed use of ShaderGenerator in registry by altering ShaderGeneratorProxy constructor to initialize _instance wth new function `virtual ShaderGenerator::getCopy()` 
fix for issue #2642
=> Fix use of custom shaderGenerator in Registry.

bootstrap-vcpkg.bat, vcpkg/vcpkg.json
Newer versions of vcpkg require a builtin-baseline setting that specifies the minimum versions of all packages, as described here: https://learn.microsoft.com/en-us/vcpkg/users/versioning#baselines and here: https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#builtin-baseline. Without this setting, bootstrap-vcpkg.bat errors out with this message:
```
[...]
-- Running vcpkg install
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.
-- Running vcpkg install - failed
[...]
```
The environment variable that contains the location of the vcpkg tool [is VCPKG_ROOT](https://learn.microsoft.com/en-us/vcpkg/users/confi …
=> Fix vcpkg config and usage

src/osgEarthDrivers/webp/CMakeLists.txt
The added code works great for WebP 1.4, but WebP 1.2 (which we support on an older Linux distro) doesn't have sharpyuv.
=> WebP: sharpyuv only added if target exists, supporting older WebP

src/osgEarth/AtlasBuilder.cpp
Fixed Linux build issue with osgEarth::optional that required a dereference due to ambiguity. Minor typos of Altus/Atlus.
=> AtlasBuilder: Fix Linux build issue, minor typos

src/osgEarth/GDAL.cpp
Version comparison appears correct (3.10), but testing demonstrated that the value was wrong for testing 3.10. I have a 3.8 GDAL that won't build without this change. Before this change, it was testing whether GDAL was greater than 3.1 instead of 3.10.
=> GDAL: Fix version comparison

src/osgEarth/MetaTile
Linux build was failing due to extra `typename` values.
On MSVC sometimes this can be caught with enforcing conformance mode using `/permissive-` compile argument (added around MSVC 2017 15.5). I did not test if this particular case was caught by that flag on Windows, was only focused on the Linux build on gcc.
=> MetaTile: Fixed erroneous typename usage

cmake/osgEarth-config.cmake.in
The `find_package(osgEarth)` sets the global include directories field for OSG, polluting the global namespace. This change isolates the include directories for OSG to only be added to targets where `osgEarth::osgEarth` is linked against. Minor clean-up.
This syntax requires CMake 3.11, but the minimum CMake version for building osgEarth is 3.20, so this should be safe from a syntax perspective.
=> osgEarth-config: Set OSG include on target instead of global

CMakeLists.txt, cmake/install-package-config-files.cmake, cmake/oe_unix.cmake, cmake/osgEarth-config.cmake.in, cmake/osgearth-macros.cmake, src/CMakeLists.txt
This is the standard way to set these on all platforms (despite the name) and does not assume a system where libraries are installed into a lib64 directory (e.g. macOS, NixOS, any 32-bit Linux).
Closes #2683.
=> Use GNUInstallDirs to handle correct platform install paths

CMakeLists.txt, cmake/install-package-config-files.cmake, cmake/osgearth-macros.cmake
Minor fixes for CMake installation support on Linux
* Minimum version fixed from 3.10 to 3.11 to avoid constant warnings about GL on configure
* Added missing Threads dependency for UNIX systems
* Capitalization fix: osgEarth-config.cmake to osgearth-config.cmake, so that `find_package(osgEarth)` can work on Linux
* Filename rename from osgEarth-configVersion.cmake, to osgearth-config-version.cmake, to match style of other file
* Install config files to share/osgEarth instead of share/osgearth, matching install location for shaders
Tested with a small Linux app that uses find_package(osgEarth). It did still require explicit links to GDAL and GEOS in the final application (Linux only) but it found the package and I was able to link successfully. Before this change, CMake could not be …
=> CMake Install: Capitalization fixes data and CMake directories; fixed include settings

CMakeLists.txt
On Windows, I was seeing plugins going to `lib/osgPlugins-3.6.5`. This changed with the recent `GNUInstallDirs` MR. Before this, on Windows it would install to `bin/osgPlugins-3.6.5`. This patch reverts to the older behavior.
I am not seeing in documentation any `GNUInstallDirs` variables that report a `lib` location on Linux, but a `bin` location on Windows (e.g. for DLL/SO files). So I used a simple if statement to swap.
=> CMake: osgPlugins on Windows now correctly goes to bin/osgPlugins

cmake/osgearth-macros.cmake
Fixes error during linking, as loadable modules can't have versions on macOS:
c++: error: invalid argument '-compatibility_version 164.0.0' only allowed with '-dynamiclib'
=> Don't add so version to modules on macOS

src/osgEarth/GLUtils.cpp
About ~L335 `GL_LINE_STIPPLE` is used. In a GL3 build of OSG, with `OSG_GL_FIXED_FUNCTION_AVAILABLE` not defined, the `GL_LINE_STIPPLE` value is also not defined. Adding `osg/LineStipple` include adds the define if necessary.
This ifxes a build error on Linux gcc 14.2 with OSG in GL3 configuration.
=> GLUtils: Line stipple now unconditionally included for GL_LINE_STIPPLE

src/osgEarthImGui/Common
I am seeing this show up as a repetitive warning when trying to build with Qt6. The ifdef stops the warning spam.
=> osgEarthImGui/Common: Avoid double-define of NOMINMAX

src/osgEarth/StringUtils
Linux builds on our end are failing on osgEarth main, simple include fix addresses the issue on usage of `std::uint64_t`
=> Add cstdint include to fix build errors on linux
