gwaldron/osgearth

src/osgEarth/HTTPClient.cpp
=> disable SSL peer verification before the data is retrieved

src/osgEarth/Map.cpp
Was not checking all the image and elevation layers for a valid profile before falling back to the default (WGS84 for geocentric, etc.)
I have an application whose TileSource has an unusual geocentric projection, and I need that ImageLayer to determine the Map's spatial reference.  Without this pull request, Map::calculateProfile() always chooses WGS84.  With this pull request, in the absence of a configured Map profile, any image or elevation layer that supplies a profile of the correct kind will determine the Map's profile.
=> Map::calculateProfile: fix fallback/default logic

src/osgEarth/ImageLayer, src/osgEarthUtil/ObjectLocator
Just some simple housekeeping.
=> Add missing C++ header comments

src/osgEarthFeatures/BuildGeometryFilter.cpp, src/osgEarthUtil/Controls.cpp
add default case in switch statement
=> Fix gcc -Wswitch warnings

docs/source/developer/shader_composition.rst
Fixed some typos in the shader documentation.
=> Fix typos in shader documentation

src/osgEarthDrivers/kml/KML_NetworkLink.cpp
=> Fix relative href in NetworkLink.

src/osgEarth/SpatialReference.cpp
http://forum.osgearth.org/SpatialReference-createLocalToWorld-problem-td7587808.html
=> Fix createLocalToWorld (MSL to ECEF)

src/osgEarth/CachePolicy, src/osgEarth/CachePolicy.cpp, src/osgEarth/TerrainLayer.cpp, src/osgEarth/optional
We are using some tools for memory validation on Linux and these fixes although they seam 'naive' fix the crashes
=> Try to fix the invalid ptr crash in debug

src/osgEarthSilverLining/CMakeLists.txt, src/osgEarthSilverLining/SilverLiningCloudsDrawable, src/osgEarthSilverLining/SilverLiningCloudsDrawable.cpp, src/osgEarthSilverLining/SilverLiningContextNode, src/osgEarthSilverLining/SilverLiningContextNode.cpp, src/osgEarthSilverLining/SilverLiningNode, src/osgEarthSilverLining/SilverLiningNode.cpp, src/osgEarthSilverLining/SilverLiningSkyDrawable, src/osgEarthSilverLining/SilverLiningSkyDrawable.cpp
Multiple camera support for the SilverLining plugin, achieved by creating a new SL-atmosphere instance for each camera (recommended way in OSG SL-samples)
=> SilverLining multi camera support

docs/source/references/drivers/model/feature_stencil.rst
=> tests: Remove doc reference to removed demo feature_stencil_line_draping.earth

src/osgEarthAnnotation/LabelNode, src/osgEarthAnnotation/LabelNode.cpp, src/osgEarthAnnotation/PlaceNode, src/osgEarthAnnotation/PlaceNode.cpp
and light performance improvements
=> Make label auto orientation working with no WGS84 data

src/osgEarth/ThreadingUtils.cpp
These changes have been included in the osgearth Debian package for a while now, but hadn't been forwarded yet.
=> Add support for GNU/Hurd & GNU/kFreeBSD

src/osgEarth/Lighting.cpp
Addresses two issues.  First, strings are not created on the fly but are instead using a static const, to prevent excessive string constructor/destructors.
Second, the setUpdateCallback for a Material Callback only called in cases where the DYNAMIC property is set.  This is intended to eliminate constant setting of uniforms in the update callback in the common case where material properties are set but not changed.
=> Lighting: Performance improvements to MaterialCallback

docs/source/faq.rst
=> periodically

src/osgEarthSymbology/GEOS, src/osgEarthSymbology/GEOS.cpp
(cherry picked from commit 6a3f724e3a19aa53ba7af40bcbce7e1e19477a8e)
=> Backport Add GEOS >= 3.6.0 compatibility 

src/osgEarth/Lighting.cpp
This is a simple modification that solves #966
=> use correct type for dynamic_cast of lights, fixes issue #966

src/osgEarth/ElevationLayer.cpp
commit 4b897935616a74503cf86e200a813fc24fc37410 optimized copying of
TileKey objects by using references, but these references could
clobber keys in the contenders array that will still be used. Scratch
space for actualKey is now used if necessary.
If the border code is re-enabled, then this bug will need to be fixed for
contenderKey as well.
The test case I used was osgearth_lights boston_projected.earth. The
bug prevents buildings from appearing.
=> Fix bug in ElevationLayerVector::populateHeightFieldAndNormalMap

src/osgEarthUtil/ViewFitter
method was declared but not implemented
=> Implement Util ViewFitter setReferenceVFOV() method

src/osgEarthDrivers/kml/KML_LabelStyle.cpp
parsing color for LabelStyle node
=> Implement KML_LabelStyle scan()

src/osgEarth/HTTPClient, src/osgEarth/HTTPClient.cpp
this allows to get the current proxy settings and allow to reset the proxy settings to not use a proxy at all
=> allow to get/reset proxy settings

src/osgEarth/Notify, src/osgEarth/Notify.cpp
and brings it up to par with OSG's Notify
this is basically a copy/paste of the current osg::Notify adapted to osgEarth.
tested against osg 3.5.10, not tested against osg 3.4.0.
=> [WIP] Notify: add the possibility to set a notification handler

src/osgEarthTriton/TritonHeightMap.cpp
=> Triton: Fix Linux build errors with g++ 4.x

src/osgEarthDrivers/engine_mp/MPGeometry.cpp
I hope it's a "correct" fix :)
=> Fix for #1147

src/applications/osgearth_package_qt/SceneController.cpp, src/osgEarthQt/TerrainProfileWidget, src/osgEarthQt/TerrainProfileWidget.cpp
Updates to ensure Qt based code builds with latest core osgEarth changes.
=> Fixes to allow Qt related files to build after 'Annotations API refactor' changes.

CMakeLists.txt
Replacing OSGEARTH QT_VERSION with DESIRED QT_VERSION to match the comment in this file and unification with osgQt
=> Fix select a specific version of Qt

tests/boston-gpu.earth
=> fix transparency on the trees

src/osgEarthFeatures/BuildGeometryFilter, src/osgEarthFeatures/BuildGeometryFilter.cpp, src/osgEarthFeatures/GeometryCompiler, src/osgEarthFeatures/GeometryCompiler.cpp, src/osgEarthFeatures/OgrUtils.cpp
add "useOSGTessellator" to select the tessellator for the geometry compiler in the feature layer
=> add useOSGTessellator to select the tessellator

src/osgEarth/HTTPClient
Added missing OSGEARTH_EXPORT commands
=> HTTPClient: fix export

CMakeModules/FindTracy.cmake
I've build Tracy from source (MacOSX) and tried to build a sample app. I haven't found an install make. @jasonbeverage, do you have found one? So, I've adapted it for the following installation:
```
lib/libtracy-release.so
include/TracyClient/Tracy.hpp
```
=> Tracy CMake update?

src/osgEarthDrivers/gltf/B3DMWriter.h
Subclass TinyGLTF and (re)implement the needed binary functions.
=> Restore binary gltf writing using stock tiny_gltf

src/osgEarthDrivers/gltf/GLTFWriter.h
accessor.count should be da->getCount() if da->getFirst() is not zero
=> fixup accessor.count in GLTFWriter

src/osgEarthDrivers/gltf/GLTFWriter.h
GLTFWriter supports double-sided materials
=> GLTFWriter supports double-sided materials

src/osgEarth/ExampleResources.cpp
=> fix: Sky does not work from earth file

src/osgEarth/WMS, src/osgEarth/WMS.cpp
Nothing critical here, just fixing up some const issues I noticed when working with WMS classes.
=> WMS: Various minor const-correctness changes.

CMakeLists.txt, src/osgEarth/Registry.cpp
This is a fix for inclined models on GDAL3/Proj6.
The only remaining issue with GDAL3 is #1516 (I a still working on it)
=> Fix for issue #1472 related to GDAL 3

.github/workflows/test/linux-vcpkg.yml
Using of ```${{ github.actor }}```
=> fix: linux-vcpkg github action

src/osgEarth/Registry.cpp
config GDAL_FILENAME_IS_UTF8 according to OSG_USE_UTF8_FILENAME
=> Update Registry.cpp, config GDAL_FILENAME_IS_UTF8 according to OSG_USE_UTF8_FILENAME

src/osgEarth/CacheBin
=> Default parameter for CacheBin constructor

.github/workflows/windows.yml
One cannot delete the cache. Try to change the key.
=> Github Action Windows: change cache key

src/osgEarth/Coverage, src/osgEarth/URI.cpp
Fixes compile issue on Linux gcc 8.3.1 on master
=> URI: Fixed gcc compile bug with temporary reference.

src/osgEarth/EarthManipulator.cpp
Short version: This is a multi-touch clean-up pass that also adds support for stationary fingers.
Longer version:
This mostly is a clean-up pass to add early-return statements in order to make the code more readable and maintainable. It also includes some fixes.
I'm working on touch integration into the SIMDIS SDK. I've made great strides and now understand the underlying structures and intentions a lot better. I've written a translation unit from Qt events to OSG events.
OSG organizes multi-touch into a `PUSH` (begin), `DRAG` (update), and `RELEASE` (end), as per `getEventType()`. `_touchPointQueue` ignores the event type, and instead looks at finger state. The code (before and after) does not look at this event type, and instead just inspects touch/finger phase. That's OK, but the …
=> EarthManipulator: Multi-touch clean-up. Implicit support for stationary fingers

docs/source/earthfile.md
Fixed xml syntax error in earthfile.md.
=> Fix syntax error in documentation

src/osgEarth/GDALDEM.cpp
Fixed typo elevaton->elevation
=> Fix typo in GDALDEM.cpp

README.md
Fix to link Github badges to correct urls.
=> fix: readme github actions badges

src/osgEarth/GLUtils.cpp
https://www.khronos.org/opengl/wiki/Debug_Output#Examples
=> Fix missing GL_APIENTRY for debug message callback

.dockerignore, Dockerfile, docker-compose.yml
This is a docker upgrade, based on my current experience on OSG and osgearth.
It uses Ubuntu 20.04.6 LTS (Focal Fossa) as base image and installs both OpenScenegraph 3.6.5 and osgearth.
@jasonbeverage, feel free to modify it as you see fit.
=> Dockerfile upgrade

.github/workflows/macos.yml
=> fix: gha macos build

src/osgEarth/OGRFeatureSource.cpp, src/osgEarth/SpatialReference.cpp
Initially I only wanted to fix building the vcpkg port with GDAL 3.11.0 (https://github.com/microsoft/vcpkg/pull/45153): Debug builds of GDAL no longer export handle types as `void*`.
But after adding the first casts I stepped into complications and ended up porting away from API which is deprecated already in GDAL 2.0 (e.g. [OGR_DS_CreateLayer()](https://gdal.org/en/stable/doxygen/ogr__api_8h.html#a424d383a37fbeaea58acaea11717f320)).
I didn't do any runtime testing, only reading docs and building the vcpkg port.
For not blocking the gdal update in vcpkg, a quick review would be helpful. (The change is probably to invasive to be accepted as a patch.) I do understand that these change need proper review. The `static_cast` might hide problems (as does `void*`). Alternatively, it would be …
=> Adopt non-deprecated GDAL 3 API; fix build with GDAL 3.11.0 debug
